export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const FETCH_USER_TRANSACTIONS = "FETCH_USER_TRANSACTIONS";
export const UPDATE_TRANSACTIONS = "UPDATE_TRANSACTIONS";
